/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        ElAvatar: typeof import('element-plus/es')['ElAvatar']
        ElBadge: typeof import('element-plus/es')['ElBadge']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElCol: typeof import('element-plus/es')['ElCol']
        ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
        ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
        ElDialog: typeof import('element-plus/es')['ElDialog']
        ElDivider: typeof import('element-plus/es')['ElDivider']
        ElDrawer: typeof import('element-plus/es')['ElDrawer']
        ElDropdown: typeof import('element-plus/es')['ElDropdown']
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
        ElEmpty: typeof import('element-plus/es')['ElEmpty']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
        ElMenu: typeof import('element-plus/es')['ElMenu']
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
        ElOption: typeof import('element-plus/es')['ElOption']
        ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
        ElPagination: typeof import('element-plus/es')['ElPagination']
        ElPopover: typeof import('element-plus/es')['ElPopover']
        ElRadio: typeof import('element-plus/es')['ElRadio']
        ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
        ElRow: typeof import('element-plus/es')['ElRow']
        ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
        ElSelect: typeof import('element-plus/es')['ElSelect']
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
        ElSwitch: typeof import('element-plus/es')['ElSwitch']
        ElTable: typeof import('element-plus/es')['ElTable']
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
        ElTabPane: typeof import('element-plus/es')['ElTabPane']
        ElTabs: typeof import('element-plus/es')['ElTabs']
        ElTag: typeof import('element-plus/es')['ElTag']
        ElTree: typeof import('element-plus/es')['ElTree']
        ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
        NavTree: typeof import('./components/NavTree.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        Sidebar: typeof import('./components/Sidebar.vue')['default']
    }

    export interface ComponentCustomProperties {
        vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    }
}
